### ISSUE TITLE
Add support for SASS/SCSS linting between style tags

### ISSUE THREAD

**Issue by allenjgreer** [thanhvg/vue#3]
Awesome job on the layer 😄. There hasn't been a lot of love for Vue in spacemacs and I'm happy to see that changing!

Quick question about the possibility of adding support for SASS/SCSS linting in the future? I'd love to try and add support for it to this layer, so if you have any ideas of how to go about that it would be awesome. May require adding a minor mode when you're between style tags??

Let me know!

**Comment by thanhvg** [comment]
Thanks for trying out this layer.

I think it is possible for SASS/SCSS linting with support from lsp backend. When you use it with lsp backend does vue lsp server lint any css? I'm asking this because i only use dumb backend. If vue lsp server won't then we may need to bring in css lsp server in. This is just my speculation for now.

**Comment by allenjgreer** [comment]
I tried it with vue-language-server and it doesn't perform any linting that I can get working. There is configuration for VS-code for SASS [here](https://vuejs.github.io/vetur/setup.html#extensions), but I'm not sure how that can translate to this layer.

**Comment by thanhvg** [comment]
I think that SASS config for VSCode only does syntax highlight which we already have. 

Flycheck supports sass/scss https://www.flycheck.org/en/latest/languages.html#sass-scss and checker chaining https://www.flycheck.org/en/latest/user/syntax-checkers.html#configuring-checker-chains. I'm not sure if the sass/scss linters can run on vue though.
